%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\KULYAH\Sem 5\KP\Data Records\Data Records\B1_Pregnancy_dataset\B1_Pregnancy_01\B1_abSignals_01.txt
%
% Auto-generated by MATLAB on 22-Jan-2021 08:26:25

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [538900, 598900];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8], "ThousandsSeparator", ",");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dat = readtable("B1_abSignals_01.txt", opts);


%% Clear temporary variables
%t = 1:length(dat.A1);
ECG_data = dat.A1;

df = fft_filter(ECG_data,1,[500/40 500/1]);

filter_ma = ma(df, 15);

s = ECG_data - filter_ma;

tes_filter_ma_inverted = -s;
[~,locs_Rwave_s] = findpeaks(tes_filter_ma_inverted,'MinPeakHeight',400,...
'MinPeakDistance',200);

jpf = length(locs_Rwave_s);
for naja = 1:jpf
s((locs_Rwave_s(naja)-21):(locs_Rwave_s(naja)+21)) = 0;
end

 %% 
figure, plot(ECG_data)
title('ECG Source');

bayi_inv = -s;
[~,locs_RBayi] = findpeaks(bayi_inv,'MinPeakHeight',80,...
'MinPeakDistance',190);

t = 1:length(s);
figure
hold on 
plot(t,s)

plot(locs_RBayi,s(locs_RBayi),'rs','MarkerFaceColor','b')
axis([0 1850 -1.1 1.1])
grid on
legend('ECG Signal','R waves')
xlabel('Samples')
ylabel('Voltage(mV)')
title('R wave Fetal with Adaptive Filter')

dataRpeak = diff(locs_RBayi);

nc = 4;
idx = kmeans(dataRpeak, nc);

sumdata = zeros(nc,1);
countdata = zeros(nc,1);
ndata = length(dataRpeak);

for i=1:ndata
    sumdata(idx(i)) = sumdata(idx(i)) + dataRpeak(i);
    countdata(idx(i)) = countdata(idx(i)) +1;
end

rata = sumdata./countdata;

sampling = 500;
dt = min(rata)/sampling;
BPM = 60/dt;